---
- get_url:
    url: "{{ consul_url }}_linux_amd64.zip"
    dest: /tmp/consul_{{ consul_version }}.zip
    validate_certs: no
    timeout: 60
  when: ansible_userspace_bits == "64"

- get_url:
    url: "{{ consul_url }}_linux_386.zip"
    dest: /tmp/consul_{{ consul_version }}.zip
    validate_certs: no
    timeout: 60
  when: ansible_userspace_bits == "32"

- group: name={{ consul_group }}
- user: name={{ consul_user }} group={{ consul_group }}

- name: create consul dir
  file: path={{ item }} state=directory owner={{ consul_user }} group={{ consul_group }}
  with_items:
    - "{{ consul_dir }}"
    - "{{ consul_dir }}/bin"
    - "{{ consul_conf_dir }}"
    - "{{ consul_data_dir }}"
    - "{{ consul_log_dir }}"

- name: unpack the consul archive
  command: "unzip /tmp/consul_{{ consul_version }}.zip -d {{ consul_dir }}/bin"
  args:
    creates: "{{ consul_dir }}/bin/consul"

- name: make link to consul folder
  file: src={{ consul_dir }} dest=/opt/consul state=link

- name: make consul executable
  file: path={{ consul_dir }}/bin/consul mode=755

- name: make consul available on the path
  alternatives: name=consul link=/usr/bin/consul path={{ consul_dir }}/bin/consul
